#pragma once
#include <eosiolib/eosio.hpp>
#include <eosiolib/asset.hpp>
#include <eosiolib/action.hpp>
#include <eosiolib/name.hpp>
#include <eosiolib/time.hpp>
#include <eosiolib/transaction.hpp>

using namespace eosio;
using std::string;

CONTRACT submerged : public eosio::contract {
  public:
    using contract::contract;
    submerged(name receiver, name code, datastream<const char*> ds): contract(receiver, code, ds) {}

    struct st_transfer {
      name from;
      name to;
      asset quantity;
      string memo;
    };

    // ======================== ACTIONS ===============================
    ACTION version();

    //subscriptions
    ACTION transfer();
    ACTION open(name owner, asset minimum_price);
    ACTION rollfunds(name content_creator, name subber);
    ACTION erasesub(name content_creator, name subber);

    //projects
    ACTION setproject(name creator, string projectId, string projectName, string contentType, uint32_t secondsToDeadline, uint64_t month);
    ACTION fulfill();
    ACTION vote();

  private:
    // ======================== HELPERS ===============================
 
    void send_money(name to, asset quantity, string msg) {
      action(
        permission_level{ _self, "active"_n },
        "eosio.token"_n,
        "transfer"_n,
        std::make_tuple(get_self(), to, quantity, msg)
      ).send();
    }

    // ======================== TABLES ===============================
    TABLE channel {
      name key;
      string sub_status;
      asset minimum_price;
      uint64_t primary_key() const { return key.value; }
    };

     TABLE subscriber {
      name key;
      asset quantity_subscribed;
      bool conditional;
      uint64_t primary_key() const { return key.value; }    
    };

    TABLE project {
      uint64_t          key; 
      bool              isActive;
      string            projectId; // what is unique to the creators table, generated by app
      string            name; // what is visible
      string            contentLink; 
      string            contentType;
      string            status; // in Progress, fulfilled, not fulfilled, payment pending
      uint64_t          month; 
      block_timestamp   due;
      block_timestamp   fulfilled;
      uint64_t primary_key() const { return key; }
    };

    typedef eosio::multi_index<"channels"_n, channel> channels_table;
    typedef eosio::multi_index<"subs"_n, subscriber> subs_table;
    typedef eosio::multi_index<"projects"_n, project> projects_table;

};